use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SettingsDto {
    pub media_flyout_enabled: bool,
    pub media_flyout_background_blur: i32,
    pub media_flyout_acrylic_window_enabled: bool,
    pub compact_layout: bool,
    pub position: i32,
    pub duration: i32,
    pub media_flyout_always_display: bool,
    pub center_title_artist: bool,
    pub player_info_enabled: bool,
    pub repeat_enabled: bool,
    pub shuffle_enabled: bool,
    pub seekbar_enabled: bool,
    pub pause_other_sessions_enabled: bool,
    pub media_flyout_volume_keys_excluded: bool,
    pub exclusive_tidal_mode: bool,
    pub next_up_enabled: bool,
    pub next_up_acrylic_window_enabled: bool,
    pub next_up_duration: i32,
    pub lock_keys_enabled: bool,
    pub lock_keys_acrylic_window_enabled: bool,
    pub lock_keys_duration: i32,
    pub lock_keys_bold_ui: bool,
    pub lock_keys_monitor_preference: i32,
    pub lock_keys_insert_enabled: bool,
    pub taskbar_widget_enabled: bool,
    pub taskbar_widget_position: i32,
    pub taskbar_widget_selected_monitor: i32,
    pub taskbar_widget_padding: bool,
    pub taskbar_widget_manual_padding: i32,
    pub taskbar_widget_clickable: bool,
    pub taskbar_widget_closeable_flyout: bool,
    pub taskbar_widget_background_blur: bool,
    pub taskbar_widget_hide_completely: bool,
    pub taskbar_widget_controls_enabled: bool,
    pub taskbar_widget_controls_position: i32,
    pub taskbar_widget_animated: bool,
    pub taskbar_visualizer_enabled: bool,
    pub taskbar_visualizer_position: i32,
    pub taskbar_visualizer_bar_count: i32,
    pub taskbar_visualizer_centered_bars: bool,
    pub taskbar_visualizer_baseline: bool,
    pub taskbar_visualizer_audio_sensitivity: i32,
    pub taskbar_visualizer_audio_peak_level: i32,
    pub taskbar_visualizer_clickable: bool,
    pub flyout_selected_monitor: i32,
    pub acrylic_blur_opacity: i32,
    pub use_album_art_as_accent_color: bool,
    pub app_language_index: i32,
    pub app_theme: i32,
    pub startup: bool,
    pub disable_if_fullscreen: bool,
    pub nicon_left_click: i32,
    pub nicon_symbol: bool,
    pub nicon_hide: bool,
    pub show_update_notifications: bool,
    pub flyout_animation_speed: i32,
    pub flyout_animation_easing_style: i32,
    pub legacy_taskbar_width_enabled: bool,
}

impl Default for SettingsDto {
    fn default() -> Self {
        Self {
            media_flyout_enabled: true,
            media_flyout_background_blur: 0,
            media_flyout_acrylic_window_enabled: true,
            compact_layout: false,
            position: 1,
            duration: 3000,
            media_flyout_always_display: false,
            center_title_artist: false,
            player_info_enabled: true,
            repeat_enabled: false,
            shuffle_enabled: false,
            seekbar_enabled: true,
            pause_other_sessions_enabled: false,
            media_flyout_volume_keys_excluded: false,
            exclusive_tidal_mode: true,
            next_up_enabled: true,
            next_up_acrylic_window_enabled: true,
            next_up_duration: 2000,
            lock_keys_enabled: true,
            lock_keys_acrylic_window_enabled: true,
            lock_keys_duration: 2000,
            lock_keys_bold_ui: false,
            lock_keys_monitor_preference: 0,
            lock_keys_insert_enabled: true,
            taskbar_widget_enabled: true,
            taskbar_widget_position: 2,
            taskbar_widget_selected_monitor: 0,
            taskbar_widget_padding: false,
            taskbar_widget_manual_padding: 0,
            taskbar_widget_clickable: true,
            taskbar_widget_closeable_flyout: true,
            taskbar_widget_background_blur: false,
            taskbar_widget_hide_completely: false,
            taskbar_widget_controls_enabled: true,
            taskbar_widget_controls_position: 1,
            taskbar_widget_animated: true,
            taskbar_visualizer_enabled: false,
            taskbar_visualizer_position: 1,
            taskbar_visualizer_bar_count: 10,
            taskbar_visualizer_centered_bars: false,
            taskbar_visualizer_baseline: false,
            taskbar_visualizer_audio_sensitivity: 2,
            taskbar_visualizer_audio_peak_level: 3,
            taskbar_visualizer_clickable: true,
            flyout_selected_monitor: 0,
            acrylic_blur_opacity: 175,
            use_album_art_as_accent_color: false,
            app_language_index: 0,
            app_theme: 0,
            startup: false,
            disable_if_fullscreen: true,
            nicon_left_click: 0,
            nicon_symbol: true,
            nicon_hide: false,
            show_update_notifications: true,
            flyout_animation_speed: 2,
            flyout_animation_easing_style: 2,
            legacy_taskbar_width_enabled: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaSessionDto {
    pub title: String,
    pub artist: String,
    pub album_art_data_url: Option<String>,
    pub playback_status: String,
    pub can_play: bool,
    pub can_pause: bool,
    pub can_previous: bool,
    pub can_next: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlyoutShowOptions {
    pub toggle_mode: bool,
    pub force_show: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MonitorDto {
    pub id: i32,
    pub name: String,
    pub left: i32,
    pub top: i32,
    pub width: i32,
    pub height: i32,
    pub is_primary: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaskbarWidgetPlacementDto {
    pub monitor_id: i32,
    pub taskbar_hwnd: String,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub dpi_scale: f64,
    pub logical_width: i32,
    pub logical_height: i32,
    pub container_x: i32,
    pub container_y: i32,
    pub container_width: i32,
    pub container_height: i32,
    pub widget_x: i32,
    pub widget_y: i32,
    pub source: String,
}
